/*
          # Initial Schema Setup
          This migration sets up the entire initial database schema for the Singularity ∞ Family application. It creates tables for user profiles, transactions, health logs, tasks, and all other core features, and links them to Supabase's built-in authentication. It also enables Row Level Security on all tables to ensure users can only access their own data.

          ## Query Description: 
          This is a foundational but safe operation for a new database. It creates the required structure without touching any existing data (as none should exist). It is essential for the application to function. No backup is needed as this is the initial setup.

          ## Metadata:
          - Schema-Category: "Structural"
          - Impact-Level: "Low"
          - Requires-Backup: false
          - Reversible: true (by dropping tables)
          
          ## Structure Details:
          - Tables Created: profiles, transactions, health_logs, notes, tasks, reminders, subscriptions, pantry_items, documents, period_logs
          - Foreign Keys: All tables are linked to `auth.users` via a `user_id` column. The `profiles` table is linked directly to the `auth.users` table's `id`.
          - Indexes: Indexes are created on `user_id` columns for performance.
          
          ## Security Implications:
          - RLS Status: Enabled on all tables.
          - Policy Changes: Yes, new RLS policies are created for all tables.
          - Auth Requirements: All operations (SELECT, INSERT, UPDATE, DELETE) will require an authenticated user.
          
          ## Performance Impact:
          - Indexes: Added on all `user_id` foreign keys to ensure fast data retrieval for authenticated users.
          - Triggers: None added in this migration.
          - Estimated Impact: Low impact on a new database, but critical for performance and security as data grows.
          */

-- 1. PROFILES TABLE
-- Stores public user data and links to auth.users
CREATE TABLE profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL PRIMARY KEY,
  updated_at TIMESTAMPTZ,
  username TEXT UNIQUE,
  full_name TEXT,
  avatar_url TEXT,
  website TEXT,
  
  CONSTRAINT username_length CHECK (char_length(username) >= 3)
);

-- RLS for profiles
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public profiles are viewable by everyone." ON profiles
  FOR SELECT USING (true);

CREATE POLICY "Users can insert their own profile." ON profiles
  FOR INSERT WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update own profile." ON profiles
  FOR UPDATE USING (auth.uid() = id);

-- Trigger to keep profiles in sync with auth.users
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, avatar_url)
  VALUES (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 2. FAMILY MEMBERS TABLE
-- Using the 'profiles' table for family members now, linked by a family_id or similar grouping mechanism in a future update.
-- For now, we add family-specific fields to the profiles table.
-- Let's adjust the members table to be a separate entity linked to a user account.

CREATE TABLE members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    name TEXT NOT NULL,
    relationship TEXT NOT NULL,
    age INT,
    gender TEXT,
    height NUMERIC,
    weight NUMERIC,
    blood_group TEXT,
    blood_pressure TEXT,
    health_status TEXT,
    diseases TEXT,
    allergies TEXT,
    health_goals TEXT,
    food_preferences TEXT[],
    taste_preferences TEXT[],
    hobbies TEXT[],
    phone TEXT,
    notes TEXT,
    is_mock BOOLEAN DEFAULT FALSE
);

ALTER TABLE members ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own family members." ON members
    FOR ALL USING (auth.uid() = user_id);
CREATE INDEX ON members(user_id);


-- 3. TRANSACTIONS TABLE
CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    type TEXT NOT NULL, -- 'income' or 'expense'
    amount NUMERIC NOT NULL,
    category TEXT NOT NULL,
    description TEXT,
    date TIMESTAMPTZ NOT NULL,
    member_ids BIGINT[],
    is_mock BOOLEAN DEFAULT FALSE
);

ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own transactions." ON transactions
    FOR ALL USING (auth.uid() = user_id);
CREATE INDEX ON transactions(user_id, date);

-- 4. HEALTH LOGS TABLE
CREATE TABLE health_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    member_id BIGINT REFERENCES members(id) ON DELETE CASCADE,
    type TEXT NOT NULL,
    value TEXT NOT NULL,
    notes TEXT,
    date TIMESTAMPTZ NOT NULL,
    is_mock BOOLEAN DEFAULT FALSE
);

ALTER TABLE health_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own health logs." ON health_logs
    FOR ALL USING (auth.uid() = user_id);
CREATE INDEX ON health_logs(user_id, member_id);

-- 5. NOTES TABLE
CREATE TABLE notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    title TEXT NOT NULL,
    content TEXT,
    date TIMESTAMPTZ NOT NULL,
    category TEXT,
    is_mock BOOLEAN DEFAULT FALSE
);

ALTER TABLE notes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own notes." ON notes
    FOR ALL USING (auth.uid() = user_id);
CREATE INDEX ON notes(user_id);

-- 6. TASKS TABLE
CREATE TABLE tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    title TEXT NOT NULL,
    description TEXT,
    completed BOOLEAN DEFAULT FALSE,
    due_date TIMESTAMPTZ,
    assigned_to BIGINT REFERENCES members(id) ON DELETE SET NULL,
    priority TEXT, -- 'low', 'medium', 'high'
    is_mock BOOLEAN DEFAULT FALSE
);

ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own tasks." ON tasks
    FOR ALL USING (auth.uid() = user_id);
CREATE INDEX ON tasks(user_id, completed);

-- 7. REMINDERS TABLE
CREATE TABLE reminders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    title TEXT NOT NULL,
    date TIMESTAMPTZ NOT NULL,
    completed BOOLEAN DEFAULT FALSE,
    notes TEXT,
    is_mock BOOLEAN DEFAULT FALSE
);

ALTER TABLE reminders ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own reminders." ON reminders
    FOR ALL USING (auth.uid() = user_id);
CREATE INDEX ON reminders(user_id);

-- 8. SUBSCRIPTIONS TABLE
CREATE TABLE subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    name TEXT NOT NULL,
    amount NUMERIC NOT NULL,
    renewal_date TIMESTAMPTZ NOT NULL,
    category TEXT,
    is_mock BOOLEAN DEFAULT FALSE
);

ALTER TABLE subscriptions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own subscriptions." ON subscriptions
    FOR ALL USING (auth.uid() = user_id);
CREATE INDEX ON subscriptions(user_id);

-- 9. PANTRY ITEMS TABLE
CREATE TABLE pantry_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    name TEXT NOT NULL,
    quantity NUMERIC NOT NULL,
    unit TEXT,
    expiry_date TIMESTAMPTZ,
    is_mock BOOLEAN DEFAULT FALSE
);

ALTER TABLE pantry_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own pantry items." ON pantry_items
    FOR ALL USING (auth.uid() = user_id);
CREATE INDEX ON pantry_items(user_id);

-- 10. DOCUMENTS TABLE
CREATE TABLE documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    name TEXT NOT NULL,
    category TEXT,
    upload_date TIMESTAMPTZ NOT NULL,
    file_url TEXT,
    is_mock BOOLEAN DEFAULT FALSE
);

ALTER TABLE documents ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own documents." ON documents
    FOR ALL USING (auth.uid() = user_id);
CREATE INDEX ON documents(user_id);

-- 11. PERIOD LOGS TABLE
CREATE TABLE period_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    start_date TIMESTAMPTZ NOT NULL,
    end_date TIMESTAMPTZ NOT NULL,
    symptoms TEXT[],
    notes TEXT,
    is_mock BOOLEAN DEFAULT FALSE
);

ALTER TABLE period_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own period logs." ON period_logs
    FOR ALL USING (auth.uid() = user_id);
CREATE INDEX ON period_logs(user_id, start_date);
